### PR TITLE
UTF-8 breaks syntax highlighting

### PR DESCRIPTION
**Pull request by Jell**
Hi there,

Having a file including UTF-8 characters breaks syntax highlighting.

If I create a file "test.rb" as follows:

```
# -*- coding: utf-8 -*-
"testöåä"
```

And try to open it, the code won't be highlighted.

### CODE REVIEW

**Comment by Jell** [comment]
Sorry for the duplicated comment, I failed in my pull request...

**Comment by jacott** [comment]
Hey Jell

I don't see your problem; in fact when I apply your patch it stops working. I'm running: GNU Emacs 23.3.1, ruby 1.9.3p134.

I also tried Emacs 24.0.94.1 with same results

**Comment by Jell** [comment]
Hum... I'm running Emacs 24.0.93 and ruby 1.9.2p290, and while running with "debug-on-error", I got `invalid US-ASCII byte in split function` on that line, that's why I decided to bypass the encoding there.

Could it be because my LC_CLANG is set to UTF-8?

Something must differ between our two settings. I'll run some more tests then.

**Comment by Jell** [comment]
I tried running ruby 1.9.3 and other stuff without success. But I wonder why my patch would break on your side? It shouldn't matter since later in the code you do:

```
tok.force_encoding(@file_encoding)
```

Also there is this snippet somewhere in the code:

```
def invalid_syntax?(code, fname='')
   code.force_encoding("utf8")
   ...
 end
```

I think this one should read:

```
 def invalid_syntax?(code, fname='')
   code.force_encoding("utf-8")
   ...
 end
```

since "utf8" is not a valid encoding name.

**Comment by jacott** [comment]
Setting LC_CLANG made no difference to my code.

Looking at your patch I would expect it to break because it will generate character positions past the end of the buffer. Try adding  force_encoding("binary") to the test_utf8_here_docs test to see what I mean.

**Comment by Jell** [comment]
Ok, no binary encoding then...

`STDIN.external_encoding` appears to be US-ASCII on my side in erm.rb, would it be possible to set it to the file/buffer encoding instead?

What about `STDIN.set_encoding("binary")`?

**Comment by jacott** [comment]
setting encoding on STDIN to binary breaks for me. setting encoding to utf-8 works.

Utf-8 should work; it is what I expect. Can you try utf-8 and send me diagnostics about exactly what is not working when you do that? Does the ruby code fail or does elisp code fail?

**Comment by Jell** [comment]
With set encoding to utf-8, in `/tmp/erm.out`, I get:

```
invalid byte sequence in UTF-8
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `split'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `block in <main>'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `open'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `<main>'
```

On the emacs side, I get:

```
Debugger entered--Lisp error: (error "Format specifier doesn't match argument type")
  format("%s%d:%d:%d:%d:%d:" "a" 0 1 18214 "nil" nil)
  byte-code("\306=\203\f\307 \210\202)p\310\311 \312\313\ned\f&\"\210\314
#\210\310
\315\"\210\316\207" [pc erm-parse-buff erm-buff-num min len erm-ruby-process dbuf erm-reparse-diff-buf process-send-string erm-ruby-get-process format "%s%d:%d:%d:%d:%d:" process-send-region "\n\n" nil max] 10)
  erm-req-parse(nil nil nil)
  ruby-fontify-buffer()
  erm-parse("\"invalid byte sequence in UTF-8: /Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `split'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `block in <main>'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `open'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `<main>'\"")
  erm-filter(#<process erm-ruby-process> "\"invalid byte sequence in UTF-8: /Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `split'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:39:in `block in <main>'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `open'\\n/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `<main>'\"\n\n")
  recursive-edit()
  debug(error (wrong-type-argument stringp nil))
  file-name-directory(nil)
  rvm-use("1.9.2-p0" "smartass --create")
  rvm-activate-corresponding-ruby()
  (lambda nil (rvm-activate-corresponding-ruby))()
  run-hooks(change-major-mode-after-body-hook ruby-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook ruby-mode-hook))
  run-mode-hooks(ruby-mode-hook)
  ruby-mode()
  set-auto-mode-0(ruby-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer price_file_validator_spec.rb> "~/Icehouse/smartass/spec/models/price_file_validator_spec.rb" nil nil "~/Icehouse/smartass/spec/models/price_file_validator_spec.rb" (10290789 234881026))
  find-file-noselect("/Users/Jell/Icehouse/smartass/spec/models/price_file_validator_spec.rb" nil nil)
  ido-file-internal(raise-frame)
  ido-find-file()
  call-interactively(ido-find-file nil nil)
```

**Comment by jacott** [comment]
So it looks like emacs is sending an invalid UTF-8 string. Can you output the byte string sent by emacs to identity where it is coming from.

like:

``` ruby
...
  c=nil
  begin
    while c=STDIN.gets("\n\0\0\0\n")
      cmd=c[0].to_sym
      args=c[1..-6].split(':',6)
      ...
  rescue
    $fixme.puts c.inspect
    $fixme.puts $!.message
    $fixme.puts $!.backtrace
    $fixme.flush
    ...
```

**Comment by Jell** [comment]
Here you go:

```
"r0:1:35:1:0:# -*- coding: utf-8 -*-\n\"test\xF6\xE5\xE4\"\n\n\x00\x00\x00\n"
invalid byte sequence in US-ASCII
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:37:in `split'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:37:in `block in <main>'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `open'
/Users/Jell/.emacs.d/el-get/Enhanced-Ruby-Mode/ruby/erm.rb:26:in `<main>'
```

**Comment by Jell** [comment]
The encoding of the string I received is actually a Latin-1 encoded string, so somewhere between the buffer and erm.rb it is encoded to Latin-1 then force_encoded to US-ASCII.

**Comment by Jell** [comment]
Ok, so doing:

```
STDIN.set_encoding("ISO-8859-1")
```

makes it work for me. Could it have something to do with `process-send-string` on the emacs side?

**Comment by Jell** [comment]
Alright! Made some changes in ruby-mode.el so that the inter process communication have the same encoding. I've used UTF-8 as the common encoding.

**Comment by jacott** [comment]
Thanks Jell!

I have merged your changes

**Pull request closed without merging**
